apiVersion: v1
kind: Service
metadata:
  name: prime-number-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: prime-number-calculator
  type: LoadBalancer